telegram:
    token: tokentokentokentokentokentokentokentokentoken
    
path:
    data: ./data
    
database: 
    connection:
        host: host.com
        port: 8888
        database: shop_main
        username: reader
        password: admin    
    cache:
        groups: database/group.csv
    
    
